import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/providers";
import TelegramProvider from "@/providers/tg";
import Header from "@/ui/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>
          <>
            <Header />
            <div className="mt-[82px] max-w-5xl">{children}</div>
          </>
        </RootProvider>
        <TelegramProvider />
      </body>
    </html>
  );
}
