import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/providers";
import TelegramProvider from "@/providers/tg";
import Header from "@/ui/layout/header";
import Footer from "@/ui/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootProvider>
          <div className="flex flex-col items-center justify-center w-full">
            <Header />
            <div className="mt-[82px]   w-full">{children}</div>
            <Footer />
          </div>
        </RootProvider>
        <TelegramProvider />
      </body>
    </html>
  );
}
